#!/bin/bash

WD=$(pwd)
DATA_DIR="${WD}/données"
OUT_DATA="${WD}/donnees.csv"

FILES=$(find "$DATA_DIR" -type f)

>"${OUT_DATA}"

for file in $FILES
do

    cat "$file" | awk -v fileName=$(basename "$file" .csv) ' {
        if ($0 != "") {
            print gensub(/([^,]*,)(.*)/, "\\1"fileName",\\2", "g", $0)
        }
    } '$'\n' >> "${OUT_DATA}"

done

cat "${OUT_DATA}"


